global:
  scrape_interval: 5s
  evaluation_interval: 5s
  
scrape_configs:

  - job_name: 'app1'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8083']
        labels:
          environment: 'local'
          service: 'api1-8083'
          application: 'api1'

  - job_name: 'app2'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8084']
        labels:
          environment: 'local'
          service: 'api2-8084'
          application: 'api2'